docs_dir: "docs"
site_dir: "../../static/midihub/docs"
site_name: Midihub Documentation
site_author: UAB VILNIAUS BLOKAS
use_directory_urls: true
theme:
  name: "material"
  favicon: "favicon.ico"
  logo: "images/logo.svg"
  palette:
    primary: "white"
    accent: "white"
  custom_dir: "blokas-docs-theme"
site_url: https://blokas.io/midihub/docs/
extra:
  google_tag_manager: "GTM-PML7W8J"
  meta_image: "https://blokas.io/images/midihub/midihub-top-dark.jpg"
  ads:
    pisound: false
    patchboxos: false
    midihub: true
    modep: false
  discourse: "https://community.blokas.io/"
  disqus: "fake"
  social:
    - type: "github"
      link: "https://github.com/BlokasLabs"
    - type: "twitter"
      link: "https://twitter.com/blokaslabs"
    - type: "facebook"
      link: "https://www.facebook.com/blokaslabs/"
repo_name: "midihub-docs"
repo_url: "https://github.com/BlokasLabs/midihub-docs/"
markdown_extensions:
  - meta
  - attr_list
  - toc:
      permalink: ""
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

copyright: "&copy; 2019-2024 VILNIAUS BLOKAS UAB"

nav:
  - Quick Start: index.md
  - The Device: device.md
  - The Editor: editor.md
  - Inserting Pipelines from File: inserting-pipelines-from-file.md
  - Inserting from Patchstorage: inserting-from-patchstorage.md
  - Insert Preview: insert-preview.md
  - MIDI Monitor: midi-monitor.md
  - Port Naming: port-naming.md
  - Pipes:
      - MIDI Input: midi-input.md
      - MIDI Output: midi-output.md
      - USB Input: usb-input.md
      - USB Output: usb-output.md
      - Virtual Input: virtual-input.md
      - Virtual Output: virtual-output.md
      - CC LFO: cc-lfo.md
      - Clock: clock.md
      - Note Length: note-length.md
      - Note Repeater: note-repeater.md
      - Arpeggiator: arpeggiator.md
      - Delay: delay.md
      - Transpose: transpose.md
      - Harmonizer: harmonizer.md
      - Dispatcher: dispatcher.md
      - Filter: filter.md
      - Channel Filter: channel-filter.md
      - Channel Range Filter: channel-range-filter.md
      - Note Range Filter: note-range-filter.md
      - CC Range Filter: cc-range-filter.md
      - Note Remap: note-remap.md
      - Channel Remap: channel-remap.md
      - CC Remap: cc-remap.md
      - Scale Remap: scale-remap.md
      - Micro Scale: micro-scale.md
      - Velocity Amp: velocity-amp.md
      - Equalizer: equalizer.md
      - Sustain: sustain.md
      - Limiter: limiter.md
      - Rescale: rescale.md
      - Transform: transform.md
      - Chance: chance.md
      - Randomizer: randomizer.md
      - Tempo Divider: tempo-divider.md
      - Sync Delay: sync-delay.md
  - MIDI Port Mapping: usb-midi-port-mapping.md

plugins:
  - search
  - redirects:
      redirect_maps:
        "midi_input.md": "midi-input.md"
        "midi_output.md": "midi-output.md"
        "usb_input.md": "usb-input.md"
        "usb_output.md": "usb-output.md"
        "virtual_input.md": "virtual-input.md"
        "virtual_output.md": "virtual-output.md"
        "cc_lfo.md": "cc-lfo.md"
        "note_length.md": "note-length.md"
        "note_repeater.md": "note-repeater.md"
        "filter_ch.md": "channel-filter.md"
        "filter_range_ch.md": "channel-range-filter.md"
        "filter_range_note.md": "note-range-filter.md"
        "filter_range_cc.md": "cc-range-filter.md"
        "note_remap.md": "note-remap.md"
        "channel_remap.md": "channel-remap.md"
        "cc_remap.md": "cc-remap.md"
        "scale_remap.md": "scale-remap.md"
        "micro_scale.md": "micro-scale.md"
        "tempo_divider.md": "tempo-divider.md"
        "sync_delay.md": "sync-delay.md"
        "the_usb_midi_port_mapping.md": "usb-midi-port-mapping.md"
