docs_dir: 'docs'
site_dir: '../../static/midihub/docs'
site_name: Midihub Documentation
site_author: UAB VILNIAUS BLOKAS
google_analytics: ['UA-44135535-1', 'auto']
use_directory_urls: true
theme:
  name: 'material'
  favicon: 'favicon.ico'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  custom_dir: 'blokas-docs-theme'
site_url: https://blokas.io/midihub/docs/
extra:
  discourse: 'https://community.blokas.io/'
  disqus: 'fake'
  social:
    - type: 'github'
      link: 'https://github.com/BlokasLabs'
    - type: 'twitter'
      link: 'https://twitter.com/blokaslabs'
    - type: 'facebook'
      link: 'https://www.facebook.com/blokaslabs/'
repo_name: 'midihub-docs'
repo_url: 'https://github.com/BlokasLabs/midihub-docs/'
markdown_extensions:
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

copyright: '&copy; 2019 VILNIAUS BLOKAS UAB'

nav:
- Introduction: index.md
- Pipes:
    - MIDI Input: midi_input.md
    - MIDI Output: midi_output.md
    - USB Input: usb_input.md
    - USB Output: usb_output.md
    - Virtual Input: virtual_input.md
    - Virtual Output: virtual_output.md
    - CC LFO: cc_lfo.md
    - Clock: clock.md
    - Note Length: note_length.md
    - Note Repeater: note_repeater.md
    - Arpeggiator: arpeggiator.md
    - Delay: delay.md
    - Transpose: transpose.md
    - Harmonizer: harmonizer.md
    - Dispatcher: dispatcher.md
    - Filter: filter.md
    - Channel Filter: filter_ch.md
    - Channel Range Filter: filter_range_ch.md
    - Note Range Filter: filter_range_note.md
    - CC Range Filter: filter_range_cc.md
    - Note Remap: note_remap.md
    - Channel Remap: channel_remap.md
    - CC Remap: cc_remap.md
    - Scale Remap: scale_remap.md
    - Micro Scale: micro_scale.md
    - Velocity Amp: velocity_amp.md
    - Equalizer: equalizer.md
    - Sustain: sustain.md
    - Limiter: limiter.md
    - Rescale: rescale.md
    - Transform: transform.md
    - Chance: chance.md
    - Randomizer: randomizer.md
    - Tempo Divider: tempo_divider.md
    - Sync Delay: sync_delay.md
- MIDI Port Mapping: the_usb_midi_port_mapping.md
